[project]
name = "example-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firecrawl-py>=4.3.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
 
 

 